import {fontOptions, fontContours, registerFontFile, validateFonts} from './font-paths.js';
import {ensurePaintUV,startRasterLayer,rasterDab,replayRasterStroke} from './raster-paint.js';
import * as THREE from 'three';
import {computeBoundsTree, disposeBoundsTree, acceleratedRaycast} from 'three-mesh-bvh';
THREE.BufferGeometry.prototype.computeBoundsTree=computeBoundsTree;
THREE.BufferGeometry.prototype.disposeBoundsTree=disposeBoundsTree;
THREE.Mesh.prototype.raycast=acceleratedRaycast;
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import agPsd from 'ag-psd/dist/bundle.js';
const {writePsd}=agPsd;
const $=id=>document.getElementById(id), rad=THREE.MathUtils.degToRad;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let toastTimer;function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4200)}
const defaults=()=>({id:crypto.randomUUID(),shape:'vase',width:1,height:1,taper:0,bulge:0,twist:0,solid:false,textVisible:true,paintVisible:true,rear:false,color:'#b9b9b6',roughness:.65,text:'FORM\nFOLLOWS\nFEELING',textColor:'#ecebdd',stroke:.013,spacing:1.13,coverage:165,textHeight:.88,textY:0,textRotation:0,mapping:'wrap',font:'mono',outline:false,rings:true,position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],strokes:[],imported:null});
let state={version:3,fonts:{},background:'#171918',objects:[defaults()],active:0,light:3,ambient:2,aspect:'free',orthographic:false,brush:{type:'acrylic',color:'#df9a65',size:.14,opacity:.9,texture:.6,spacing:.025,pressure:true}};
let tab='shape',mode='orbit',busy=false,history=[],future=[],lastSnapshot;
const scene=new THREE.Scene();scene.background=new THREE.Color(state.background);
const perspective=new THREE.PerspectiveCamera(32,1,.01,200);perspective.position.set(0,1.5,10.8);
const ortho=new THREE.OrthographicCamera(-3,3,3,-3,.01,200);let camera=perspective;
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true})}catch(e){$('canvas').innerHTML='<p class="note" style="padding:40px;color:white">WebGL is unavailable. Please enable hardware acceleration in your browser to use the 3D studio.</p>';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(state.background,1);$('canvas').appendChild(renderer.domElement);
let controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=3;controls.maxDistance=35;
const ambient=new THREE.AmbientLight(0xffffff,state.ambient);scene.add(ambient);
const light=new THREE.DirectionalLight(0xffffff,state.light);light.position.set(-3,6,5);scene.add(light);
const rim=new THREE.DirectionalLight(0xffffff,1.7);rim.position.set(4,2,-3);scene.add(rim);
const world=new THREE.Group();scene.add(world);const ray=new THREE.Raycaster();let models=[];
const glyphs={
A:'0,0 .5,1 1,0|.2,.4 .8,.4',B:'0,0 0,1 .62,1 .9,.88 .9,.65 .62,.52 0,.52|.62,.52 1,.38 1,.15 .65,0 0,0',
C:'1,.9 .75,1 .25,1 0,.8 0,.2 .25,0 .75,0 1,.1',D:'0,0 0,1 .55,1 .85,.85 1,.6 1,.4 .85,.15 .55,0 0,0',
E:'1,1 0,1 0,0 1,0|0,.52 .8,.52',F:'0,0 0,1 1,1|0,.53 .8,.53',G:'1,.85 .75,1 .25,1 0,.8 0,.2 .25,0 .75,0 1,.2 1,.5 .55,.5',
H:'0,0 0,1|1,0 1,1|0,.5 1,.5',I:'.5,0 .5,1|.15,1 .85,1|.15,0 .85,0',
J:'0,.2 .2,0 .65,0 1,.25 1,1',K:'0,0 0,1|1,1 0,.45 1,0',L:'0,1 0,0 1,0',
M:'0,0 0,1 .5,.25 1,1 1,0',N:'0,0 0,1 1,0 1,1',
O:'.25,0 0,.2 0,.8 .25,1 .75,1 1,.8 1,.2 .75,0 .25,0',
P:'0,0 0,1 .7,1 1,.8 1,.65 .7,.5 0,.5',Q:'.25,0 0,.2 0,.8 .25,1 .75,1 1,.8 1,.2 .75,0 .25,0|.6,.25 1,-.1',
R:'0,0 0,1 .7,1 1,.8 1,.65 .7,.5 0,.5|.5,.5 1,0',
S:'1,.85 .75,1 .25,1 0,.8 0,.65 .25,.5 .75,.5 1,.35 1,.2 .75,0 .25,0 0,.15',
T:'0,1 1,1|.5,1 .5,0',U:'0,1 0,.25 .2,0 .8,0 1,.25 1,1',V:'0,1 .5,0 1,1',
W:'0,1 .25,0 .5,.65 .75,0 1,1',X:'0,1 1,0|0,0 1,1',Y:'0,1 .5,.5 1,1|.5,.5 .5,0',Z:'0,1 1,1 0,0 1,0',
'0':'.25,0 0,.2 0,.8 .25,1 .75,1 1,.8 1,.2 .75,0 .25,0',
'1':'.2,.8 .5,1 .5,0|.1,0 .9,0','2':'0,.8 .25,1 .75,1 1,.8 1,.65 0,0 1,0','3':'0,1 1,1 .5,.5 1,.35 1,.15 .75,0 0,0',
'4':'.8,0 .8,1 0,.35 1,.35','5':'1,1 0,1 0,.5 .75,.5 1,.3 1,.15 .75,0 0,0','6':'1,1 .3,1 0,.7 0,.2 .2,0 .8,0 1,.2 1,.4 .8,.55 0,.55',
'7':'0,1 1,1 .2,0','8':'.25,.5 0,.7 0,.85 .25,1 .75,1 1,.85 1,.7 .75,.5 .25,.5 0,.3 0,.15 .25,0 .75,0 1,.15 1,.3 .75,.5',
'9':'1,.45 .2,.45 0,.6 0,.8 .2,1 .8,1 1,.8 1,.3 .7,0 0,0',
'.':'.45,0 .55,0','-':'0,.5 1,.5','!':'.5,.3 .5,1|.5,0 .51,0','?':'0,.8 .2,1 .8,1 1,.8 .5,.4 .5,.3|.5,0 .51,0',
'&':'1,0 .15,.65 .15,.85 .35,1 .6,1 .8,.8 .7,.6 .15,.35 0,.15 .2,0 .6,0 1,.45'
};
function clearGroup(g){while(g.children.length){const c=g.children[0];g.remove(c);c.traverse(x=>{x.geometry?.disposeBoundsTree?.();x.geometry?.dispose();if(x.material){(Array.isArray(x.material)?x.material:[x.material]).forEach(m=>{m.map?.dispose();m.dispose()})}})}}
function radius(t,o){let r;switch(o.shape){case 'milkjar':{
 const profile=[[0,.85],[.025,.97],[.55,.97],[.64,.91],[.77,.48],[.87,.43],[.89,.5],[.95,.5],[.975,.43],[1,.43]];
 const end=profile.findIndex(p=>p[0]>=t),i=Math.max(1,end);const a=profile[i-1],b=profile[i];r=THREE.MathUtils.lerp(a[1],b[1],(t-a[0])/(b[0]-a[0]));break}
 case 'cylinder':r=1;break;case 'cup':r=.75+.38*t;break;case 'bowl':r=Math.sqrt(Math.max(.04,1-Math.pow(1-t,2)))*1.6;break;case 'sphere':r=Math.sqrt(Math.max(.0001,1-Math.pow(t*2-1,2)))*1.5;break;default:r=.82+.61*Math.sin(Math.PI*t)-.73*Math.exp(-Math.pow((t-.85)/.19,2))+.22*Math.exp(-Math.pow((t-1)/.055,2))}
return Math.max(.06,r*(1+o.taper*(t-.5))+o.bulge*Math.sin(t*Math.PI))}
function baseHeight(o){return o.shape==='bowl'?1.7:o.shape==='sphere'?3:3.7}

function milkPackGeometry(){
 const rings=[[-1.85,.94,.7],[.95,.94,.7],[1.64,.94,.025],[1.85,.94,.025]];
 const vertices=rings.flatMap(([y,x,z])=>[[-x,y,z],[x,y,z],[x,y,-z],[-x,y,-z]]);
 const positions=[];
 const face=(a,b,c)=>{for(const i of [a,b,c])positions.push(...vertices[i])};
 for(let r=0;r<3;r++)for(let j=0;j<4;j++){const a=r*4+j,b=r*4+(j+1)%4,c=(r+1)*4+(j+1)%4,d=(r+1)*4+j;face(a,b,c);face(a,c,d)}
 face(0,2,1);face(0,3,2);face(12,13,14);face(12,14,15);
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.computeVertexNormals();return g;
}
function shapeName(shape){return ({milkjar:'Milk jar',milkpack:'Milk pack',imported:'Imported form'})[shape]||shape[0].toUpperCase()+shape.slice(1)}

function geometryFor(o){let g;if(o.shape==='imported'&&o.imported){g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(o.imported.positions,3));if(o.imported.indices)g.setIndex(o.imported.indices);g.computeVertexNormals()}else if(o.shape==='milkpack'){g=milkPackGeometry()}else if(o.shape==='torus'){g=new THREE.TorusGeometry(1.15,.46,32,100);g.rotateX(Math.PI/2)}else{const pts=[],h=baseHeight(o);for(let i=0;i<=100;i++){const t=i/100;pts.push(new THREE.Vector2(radius(t,o),(t-.5)*h))}g=new THREE.LatheGeometry(pts,128)}
g=ensurePaintUV(g);const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),a=rad(o.twist)*y/3;const factor=o.shape==='milkpack'?Math.max(.2,1+o.taper*y/3.7+o.bulge*Math.cos(y/3.7*Math.PI)):1;p.setXYZ(i,(x*Math.cos(a)-z*Math.sin(a))*o.width*factor,y*o.height,(x*Math.sin(a)+z*Math.cos(a))*o.width*factor)}g.computeVertexNormals();g.computeBoundingBox();g.computeBoundsTree();return g}
function surface(u,v,o,model){const a=u*Math.PI*2+rad(o.textRotation),box=model.base.geometry.boundingBox;const y=THREE.MathUtils.lerp(box.min.y+.018,box.max.y-.018,v);
if(o.mapping==='project'){const x=THREE.MathUtils.lerp(box.min.x,box.max.x,u+.5);ray.set(new THREE.Vector3(x,y,box.max.z+10),new THREE.Vector3(0,0,-1))}
else ray.set(new THREE.Vector3(Math.sin(a)*20,y,Math.cos(a)*20),new THREE.Vector3(-Math.sin(a),0,-Math.cos(a)));
const hit=ray.intersectObject(model.proxy,false)[0];if(!hit)return null;
return hit.point.clone().addScaledVector(hit.face.normal,.022+o.stroke*.3)}
function lineMesh(points,color,size,opacity=1){if(points.length<2)return null;const curve=new THREE.CatmullRomCurve3(points,false,'centripetal');const geo=new THREE.TubeGeometry(curve,Math.min(700,Math.max(points.length*2,12)),size,5,false);const mat=new THREE.MeshBasicMaterial({color,transparent:opacity<1,opacity});const mesh=new THREE.Mesh(geo,mat);mesh.userData.path=points.map(p=>p.toArray());mesh.userData.width=size*2;return mesh}
function addMapped(points,o,m,color=o.textColor,width=o.stroke){let segment=[];const finish=()=>{const line=lineMesh(segment,color,width);if(line)m.text.add(line);segment=[]};for(const uv of points){const p=surface(uv[0],uv[1],o,m);if(p){if(segment.length&&segment.at(-1).distanceTo(p)>.35)finish();segment.push(p)}else finish()}finish()}
function makeText(o,m){clearGroup(m.text);const rows=(['mono','slant'].includes(o.font)?o.text.toUpperCase():o.text).split('\n').slice(0,8),n=rows.length;const cov=o.coverage/360;const yBottom=.5-o.textHeight/2+o.textY;rows.forEach((row,r)=>{
if(!['mono','slant'].includes(o.font)){
 const contours=fontContours(row,o.font,state.fonts||{},o.spacing);
 for(const contour of contours)addMapped(contour.map(([x,y])=>[-.5*cov+x*cov,yBottom+((n-r-1)+.08+y*.82)*o.textHeight/n]),o,m);
 return;
}
const chars=[...row].slice(0,44),stride=cov/Math.max(1,chars.length),letter=stride/o.spacing;for(let i=0;i<chars.length;i++){const paths=glyphs[chars[i]];if(!paths)continue;for(const path of paths.split('|')){const nodes=path.split(' ').map(p=>p.split(',').map(Number));const pts=[];for(let j=1;j<nodes.length;j++){const p0=nodes[j-1],p1=nodes[j],d=Math.hypot(p1[0]-p0[0],p1[1]-p0[1]);for(let s=0;s<=Math.max(3,Math.ceil(d*20));s++){const t=s/Math.max(3,Math.ceil(d*20));let x=p0[0]+(p1[0]-p0[0])*t,y=p0[1]+(p1[1]-p0[1])*t;if(o.font==='slant')x+=y*.16;pts.push([-.5*cov+i*stride+x*letter,yBottom+((n-r-1)+.08+y*.82)*o.textHeight/n])}}if(o.outline){for(const shift of [-.003,.003])addMapped(pts.map(p=>[p[0]+shift,p[1]]),o,m)}else addMapped(pts,o,m)}}});
if(o.rings)for(const v of [.035,.065,.945,.975]){const pts=[];for(let j=0;j<=220;j++)pts.push([j/220,v]);addMapped(pts,o,m)}m.text.visible=o.textVisible}
function makePaint(o,m){clearGroup(m.paint);if(o.strokes.length){startRasterLayer(o,m);for(const stroke of o.strokes)replayRasterStroke(stroke,m)}else{m.paintCanvas=null;m.paintTexture=null;m.paintStamps=null}m.paint.visible=o.paintVisible}
function hasPainting(){return state.objects.some(o=>o.strokes.some(s=>s.type!=='eraser'))}
function applyTransform(o,m){m.group.position.fromArray(o.position);m.group.rotation.set(...o.rotation.map(rad));m.group.scale.fromArray(o.scale);m.group.updateMatrixWorld(true)}
function visibility(o,m){m.base.visible=true;m.base.material.colorWrite=o.solid;m.base.material.depthWrite=o.solid||!o.rear;m.base.material.color.set(o.color);m.base.material.roughness=o.roughness;m.text.visible=o.textVisible;m.paint.visible=o.paintVisible}
function rebuild(){for(const m of models)m.proxy.material.dispose();clearGroup(world);models=[];for(const o of state.objects){const group=new THREE.Group(),geometry=geometryFor(o),base=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:o.color,roughness:o.roughness,side:THREE.DoubleSide}));base.renderOrder=-1;const proxy=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({side:THREE.DoubleSide}));proxy.updateMatrixWorld(true);const m={group,base,proxy,text:new THREE.Group(),paint:new THREE.Group()};group.add(base,m.text,m.paint);world.add(group);models.push(m);makeText(o,m);makePaint(o,m);applyTransform(o,m);visibility(o,m)}scene.background=new THREE.Color(state.background);ambient.intensity=state.ambient;light.intensity=state.light;syncLayers()}

function remapPainting(o,key,value){
 const m=models[state.active],oldGeometry=m.base.geometry;
 const next={...o,[key]:value};
 if(key==='shape'){o.strokes=[];toast('New shape selected. Painting cleared; Undo restores it.');return}
 const newGeometry=geometryFor(next),a=oldGeometry.attributes.position,b=newGeometry.attributes.position;
 if(a.count!==b.count){newGeometry.dispose();return}
 const index=oldGeometry.index,closest={};
 for(const stroke of o.strokes)for(let j=0;j<stroke.points.length;j++){
  const p=new THREE.Vector3(...stroke.points[j]);
  oldGeometry.boundsTree.closestPointToPoint(p,closest);
  if(closest.faceIndex===undefined)continue;
  const n=closest.faceIndex*3,ids=[0,1,2].map(k=>index?index.getX(n+k):n+k);
  const oldTri=new THREE.Triangle(...ids.map(i=>new THREE.Vector3().fromBufferAttribute(a,i)));
  const bary=oldTri.getBarycoord(closest.point,new THREE.Vector3());
  if(!bary)continue;
  const verts=ids.map(i=>new THREE.Vector3().fromBufferAttribute(b,i));
  const normal=new THREE.Triangle(...verts).getNormal(new THREE.Vector3());
  const pt=verts[0].multiplyScalar(bary.x).addScaledVector(verts[1],bary.y).addScaledVector(verts[2],bary.z).addScaledVector(normal,.026);
  stroke.points[j]=pt.toArray();
 }
 newGeometry.disposeBoundsTree();newGeometry.dispose();
}

function active(){return state.objects[state.active]}function syncLayers(){$('layers').innerHTML=state.objects.map((o,i)=>'<div class="layer '+(i===state.active?'active':'')+'" data-layer="'+i+'" role="button" tabindex="0"><span class="layer-icon">◒</span><div>'+esc(shapeName(o.shape))+' '+String(i+1).padStart(2,'0')+'<small>'+esc(o.text.split('\n')[0]||'No lettering')+'</small></div><button class="delete" data-delete="'+i+'" aria-label="Delete form '+(i+1)+'">×</button></div>').join('');const o=active();for(const [id,key] of [['solidToggle','solid'],['textToggle','textVisible'],['paintToggle','paintVisible'],['rearToggle','rear']])$(id).checked=o[key];$('background').value=state.background;$('stage').style.background=state.background;$('workTitle').textContent=shapeName(o.shape)+' study';}
function snapshot(){return JSON.stringify(state)}function commit(){const now=snapshot();if(lastSnapshot!==now){if(lastSnapshot)history.push(lastSnapshot);if(history.length>25)history.shift();while(history.length>1&&history.reduce((n,s)=>n+s.length,0)>25000000)history.shift();lastSnapshot=now;future=[]}syncHistory()}
function syncHistory(){$('undo').disabled=!history.length;$('redo').disabled=!future.length}
function restore(s){state=JSON.parse(s);lastSnapshot=s;rebuild();renderSettings();syncHistory()}
function undo(){if(busy||!history.length)return;future.push(lastSnapshot);restore(history.pop())}
function redo(){if(busy||!future.length)return;history.push(lastSnapshot);restore(future.pop())}
function slider(label,key,min,max,step,value){return '<label class="control slider"><span class="range-title">'+label+'<output>'+value+'</output></span><input aria-label="'+label+'" data-key="'+key+'" type="range" min="'+min+'" max="'+max+'" step="'+step+'" value="'+value+'"></label>'}
function select(label,key,options,value){return '<label class="control">'+label+'<select data-key="'+key+'">'+options.map(([v,l])=>'<option value="'+esc(v)+'" '+(v===value?'selected':'')+'>'+esc(l)+'</option>').join('')+'</select></label>'}
function check(label,key,val){return '<label class="switch-row">'+label+'<input type="checkbox" data-key="'+key+'" '+(val?'checked':'')+'></label>'}
function color(label,key,val){return '<label class="control">'+label+'<input type="color" data-key="'+key+'" value="'+val+'"></label>'}
function axes(label,key,values){return '<div class="axis-heading">'+label+'</div><div class="axis-grid">'+['X','Y','Z'].map((a,i)=>'<label>'+a+'<input aria-label="'+label+' '+a+'" type="number" step="'+(key==='rotation'?5:.1)+'" data-axis="'+key+'" data-index="'+i+'" value="'+values[i]+'"></label>').join('')+'</div>'}
function renderSettings(){const o=active();let h='';if(tab==='shape'){h='<div class="section-label">THE FORM</div>'+select('Shape','shape',[['vase','Vase'],['cup','Cup'],['bowl','Bowl'],['sphere','Sphere'],['cylinder','Cylinder'],['torus','Torus'],['milkjar','Milk jar'],['milkpack','Milk pack'],...(o.imported?[['imported','Imported']]:[])],o.shape)+slider('Width','width',.4,2,.01,o.width)+slider('Height','height',.4,2,.01,o.height)+slider('Taper','taper',-.9,.9,.01,o.taper)+slider('Curvature','bulge',-.4,.6,.01,o.bulge)+slider('Twist','twist',-180,180,1,o.twist)+'<button id="importModel" class="upload">↑ &nbsp; Import a 3D model</button><div class="section-label">SURFACE</div>'+check('Show solid form','solid',o.solid)+color('Material','color',o.color)+slider('Roughness','roughness',0,1,.01,o.roughness)+'<p class="note">STL, OBJ, GLB or glTF. Files stay on your device.</p>'}
if(tab==='text'){h='<div class="section-label">YOUR WORDS</div><textarea aria-label="Text to wrap" data-key="text" maxlength="250">'+esc(o.text)+'</textarea>'+select('Font','font',fontOptions(state.fonts||{}),o.font)+'<button class="upload" id="importFont">＋ Import font from Files</button>'+select('Mapping','mapping',[['wrap','Wrap around'],['project','Front projection']],o.mapping)+color('Stroke color','textColor',o.textColor)+slider('Stroke width','stroke',.005,.06,.001,o.stroke)+slider('Wrap angle','coverage',30,355,1,o.coverage)+slider('Letter spacing','spacing',1,2,.01,o.spacing)+slider('Text height','textHeight',.1,.96,.01,o.textHeight)+slider('Move vertically','textY',-.35,.35,.01,o.textY)+slider('Around surface','textRotation',-180,180,1,o.textRotation)+check('Double-line lettering','outline',o.outline)+check('Rim lines','rings',o.rings)+check('Show lettering','textVisible',o.textVisible)+'<p class="note">Choose a font or import TTF, OTF or WOFF from Files. Imported fonts use outline strokes and are saved with your project. Monoline uses A–Z. Enter adds a row.</p>'}
if(tab==='paint'){h='<div class="section-label">ON THE SURFACE</div>'+select('Brush','brush.type',[['acrylic','Acrylic'],['pastel','Pastel'],['pen','Fine pen'],['eraser','Soft eraser']],state.brush.type)+color('Color','brush.color',state.brush.color)+slider('Size','brush.size',.02,.5,.005,state.brush.size)+slider('Opacity','brush.opacity',.1,1,.05,state.brush.opacity)+slider('Texture','brush.texture',0,1,.05,state.brush.texture)+slider('Spacing','brush.spacing',.005,.1,.005,state.brush.spacing)+check('Pen pressure','brush.pressure',state.brush.pressure)+'<button class="primary wide" id="startPaint">'+(mode==='paint'?'Switch to orbit':'Paint on the form')+'</button><div class="mini-actions"><button id="clearPaint">Clear painting</button></div><p class="note">Draw with a finger or Apple Pencil. Tap Move to orbit or pinch to zoom. Paint is a 2048 px raster texture. Acrylic has bristle marks; pastel has grain. SVG is unavailable while painting is present.</p>'}
if(tab==='scene'){h='<div class="section-label">TRANSFORM SELECTED FORM</div>'+axes('Position','position',o.position)+axes('Rotation','rotation',o.rotation)+axes('Scale','scale',o.scale)+'<div class="mini-actions"><button id="duplicate">Duplicate</button><button id="addHere">Add form</button></div><div class="section-rule"></div><div class="section-label">THE SCENE</div>'+color('Background','scene.background',state.background)+slider('Key light','scene.light',0,8,.1,state.light)+slider('Ambient light','scene.ambient',0,5,.1,state.ambient)+select('Artboard','scene.aspect',[['free','Fit window'],['1','Square'],['.8','Portrait 4:5'],['1.7778','Landscape 16:9']],state.aspect)+check('Orthographic camera','scene.orthographic',state.orthographic)+check('Show rear strokes','rear',o.rear)}
$('settings').innerHTML=h;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
$('settings').querySelectorAll('[data-key]').forEach(el=>{el.addEventListener('input',()=>{if(busy)return;let v=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;let k=el.dataset.key;if(el.type==='range')el.parentElement.querySelector('output').textContent=v;if(k.startsWith('brush.'))state.brush[k.split('.')[1]]=v;else if(k.startsWith('scene.')){state[k.split('.')[1]]=v;if(k==='scene.orthographic')switchCamera();if(k==='scene.aspect')setAspect();scene.background=new THREE.Color(state.background);ambient.intensity=state.ambient;light.intensity=state.light;syncLayers()}else{if(['shape','width','height','taper','bulge','twist'].includes(k)&&o.strokes.length)remapPainting(o,k,v);o[k]=v;if(['solid','color','roughness','textVisible','paintVisible','rear'].includes(k)){visibility(o,models[state.active]);syncLayers()}else rebuild()} });el.addEventListener('change',commit)});
$('settings').querySelectorAll('[data-axis]').forEach(el=>el.addEventListener('change',()=>{const v=Number(el.value);if(!Number.isFinite(v))return;const arr=o[el.dataset.axis];arr[Number(el.dataset.index)]=el.dataset.axis==='scale'?Math.max(.05,Math.min(5,v)):Math.max(-360,Math.min(360,v));applyTransform(o,models[state.active]);commit()}));
if($('importFont'))$('importFont').onclick=()=>$('fontFile').click();if($('importModel'))$('importModel').onclick=()=>$('modelFile').click();if($('startPaint'))$('startPaint').onclick=()=>{setMode(mode==='paint'?'orbit':'paint');renderSettings()};if($('clearPaint'))$('clearPaint').onclick=()=>{o.strokes=[];makePaint(o,models[state.active]);commit();toast('Painting cleared. Undo to bring it back.')};if($('duplicate'))$('duplicate').onclick=duplicate;if($('addHere'))$('addHere').onclick=addObject;
}
function setMode(v){mode=v;controls.enabled=v==='orbit';$('orbitTool').classList.toggle('selected',v==='orbit');$('brushTool').classList.toggle('selected',v==='paint');renderer.domElement.style.cursor=v==='paint'?'crosshair':'grab';$('hint').textContent=v==='paint'?'Draw on the form · Tap Move to orbit or zoom · Undo above':'One finger: orbit · Two fingers: pan & zoom'}
function resize(){if(busy)return;const w=$('canvas').clientWidth,h=$('canvas').clientHeight;renderer.setSize(w,h);perspective.aspect=w/h;perspective.updateProjectionMatrix();ortho.left=-3*w/h;ortho.right=3*w/h;ortho.top=3;ortho.bottom=-3;ortho.updateProjectionMatrix()}
function setAspect(){const st=$('stage');if(state.aspect==='free'){st.style.aspectRatio='';st.style.height=''}else{st.style.aspectRatio=state.aspect;st.style.height='auto'}resize()}
function switchCamera(){const old=camera;camera=state.orthographic?ortho:perspective;camera.position.copy(old.position);camera.quaternion.copy(old.quaternion);const target=controls.target.clone();controls.dispose();controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(target);controls.enableDamping=true;controls.enabled=mode==='orbit';$('zoomReadout').textContent=state.orthographic?'ORTHOGRAPHIC':'PERSPECTIVE';resize()}
function addObject(){if(state.objects.length>=8)return toast('This composition supports up to 8 forms.');const o=defaults();o.position=[state.objects.length*1.2,0,0];o.scale=[.7,.7,.7];state.objects.push(o);state.active=state.objects.length-1;rebuild();renderSettings();commit();toast('New form added. Position it in Scene.')}
function duplicate(){const o=JSON.parse(JSON.stringify(active()));o.id=crypto.randomUUID();o.position[0]+=1.5;if(state.objects.length>=8)return toast('Maximum 8 forms.');state.objects.push(o);state.active=state.objects.length-1;rebuild();renderSettings();commit()}
$('layers').addEventListener('click',e=>{if(busy)return;const del=e.target.closest('[data-delete]');if(del){if(state.objects.length===1)return toast('Keep at least one form in your study.');state.objects.splice(+del.dataset.delete,1);state.active=Math.min(state.active,state.objects.length-1);rebuild();renderSettings();commit();return}const l=e.target.closest('[data-layer]');if(l){state.active=+l.dataset.layer;syncLayers();renderSettings()}});
$('layers').addEventListener('keydown',e=>{if(e.key==='Enter')e.target.click()});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderSettings()});
for(const [id,key] of [['solidToggle','solid'],['textToggle','textVisible'],['paintToggle','paintVisible'],['rearToggle','rear']])$(id).onchange=e=>{active()[key]=e.target.checked;visibility(active(),models[state.active]);renderSettings();commit()};
$('background').oninput=e=>{state.background=e.target.value;scene.background=new THREE.Color(state.background);syncLayers()};$('background').onchange=commit;
document.querySelectorAll('[data-bg]').forEach(b=>b.onclick=()=>{state.background=b.dataset.bg;scene.background=new THREE.Color(state.background);syncLayers();commit()});
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const o=defaults();o.shape=b.dataset.preset;if(o.shape==='bowl'){o.text='SLOW\nMOMENTS';o.coverage=170}state.objects[state.active]=o;rebuild();renderSettings();commit()});
$('addObject').onclick=addObject;$('undo').onclick=undo;$('redo').onclick=redo;$('orbitTool').onclick=()=>setMode('orbit');$('brushTool').onclick=()=>{tab='paint';setMode('paint');renderSettings()};
function view(x,y,z){camera.position.set(x,y,z);controls.target.set(0,0,0);camera.zoom=1;camera.updateProjectionMatrix();controls.update()}
$('frontView').onclick=()=>view(0,0,10.8);$('sideView').onclick=()=>view(10.8,0,0);$('topView').onclick=()=>view(0,10.8,.001);$('resetView').onclick=()=>view(0,1.5,10.8);
$('help').onclick=()=>toast('Move: one finger to orbit, two to pan and zoom. Paint: draw with a finger or Pencil. Use the Undo button to step back.');
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if(e.key==='Alt'&&mode==='paint')controls.enabled=true});
window.addEventListener('keyup',e=>{if(e.key==='Alt'&&mode==='paint')controls.enabled=false});
new ResizeObserver(resize).observe($('canvas'));
rebuild();renderSettings();commit();resize();setMode('orbit');
renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
window.addEventListener('beforeunload',e=>{if(history.length){e.preventDefault();e.returnValue=''}});
window.formline={getState:()=>JSON.parse(snapshot()),getScene:()=>scene,getCamera:()=>camera};

// Real raster dabs projected onto local surface triangles and painted in UV space.
let drawing=null,lastDraw=null;
function pickSurface(e){const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const m=models[state.active];m.group.updateMatrixWorld(true);const hit=ray.intersectObject(m.base,false)[0];return hit?m.group.worldToLocal(hit.point.clone()):null}
function pressureAt(e){return state.brush.pressure&&e.pointerType==='pen'?Math.max(.15,e.pressure):1}
renderer.domElement.addEventListener('pointerdown',e=>{
 if(mode!=='paint'||e.altKey||e.button!==0||busy)return;
 const p=pickSurface(e);if(!p)return;
 const o=active(),m=models[state.active],b=state.brush;
 if(o.strokes.length>=2000)return toast('Stroke limit reached. Save this study before starting another.');
 controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);
 drawing={id:crypto.randomUUID(),seed:Math.floor(Math.random()*4294967295),type:b.type,color:b.color,size:b.size,opacity:b.opacity,texture:b.texture,points:[p.toArray()],pressures:[pressureAt(e)]};
 o.strokes.push(drawing);if(!m.paintCanvas)startRasterLayer(o,m);
 rasterDab(drawing,m,p,pressureAt(e));lastDraw=p;
});
renderer.domElement.addEventListener('pointermove',e=>{
 if(!drawing||e.altKey)return;const p=pickSurface(e);
 if(!p){endDraw();return}
 const d=lastDraw.distanceTo(p);if(d>Math.max(.6,drawing.size*8)){endDraw();return}
 if(d<Math.min(state.brush.spacing,drawing.size*.25))return;
 const count=Math.max(1,Math.ceil(d/Math.max(.005,drawing.size*.2)));
 for(let i=1;i<=count;i++)rasterDab(drawing,models[state.active],lastDraw.clone().lerp(p,i/count),pressureAt(e));
 drawing.points.push(p.toArray());drawing.pressures.push(pressureAt(e));lastDraw=p;
 if(drawing.points.length>=14000){endDraw();toast('Stroke saved. Continue with a new stroke.')}
});
function endDraw(){if(drawing){drawing=null;lastDraw=null;commit()}}
renderer.domElement.addEventListener('pointerup',endDraw);renderer.domElement.addEventListener('pointercancel',endDraw);

function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000)}
$('saveProject').onclick=()=>{const project={...state,camera:{position:camera.position.toArray(),target:controls.target.toArray(),zoom:camera.zoom}};download(new Blob([JSON.stringify(project)],{type:'application/json'}),'study-V03.formline');toast('Editable project saved.')};
$('openProject').onclick=()=>$('projectFile').click();
function validateProject(d){if(!d||![1,2,3].includes(d.version)||!Array.isArray(d.objects)||!d.objects.length||d.objects.length>8)throw Error('This is not a supported Formline project.');const types=['vase','cup','bowl','sphere','cylinder','torus','milkjar','milkpack','imported'];for(const o of d.objects){if(!types.includes(o.shape)||typeof o.text!=='string'||o.text.length>250||!Array.isArray(o.strokes))throw Error('Invalid form data.');for(const k of ['position','rotation','scale'])if(!Array.isArray(o[k])||o[k].length!==3||o[k].some(v=>!Number.isFinite(v)))throw Error('Invalid transform.');for(const k of ['width','height','taper','bulge','twist','stroke','spacing','coverage','textHeight','textY','textRotation','roughness'])if(!Number.isFinite(o[k]))throw Error('Invalid controls.');if(o.stroke<.001||o.stroke>.2||o.width<.05||o.width>10||o.height<.05||o.height>10||o.spacing<.1)throw Error('Controls are outside supported limits.');if(o.strokes.length>2000||o.strokes.some(s=>!Array.isArray(s.points)||s.points.length>15000||s.points.some(p=>!Array.isArray(p)||p.length!==3||p.some(v=>!Number.isFinite(v)))||!Number.isFinite(s.size)||s.size<=0||!['acrylic','pastel','pen','eraser'].includes(s.type)||!Number.isFinite(s.opacity)||s.opacity<0||s.opacity>1||!Number.isFinite(s.texture)||s.texture<0||s.texture>1||(s.pressures&&(!Array.isArray(s.pressures)||s.pressures.length!==s.points.length||s.pressures.some(p=>!Number.isFinite(p)||p<.01||p>1)))))throw Error('Invalid painting.');if(o.imported&&(!Array.isArray(o.imported.positions)||o.imported.positions.length>1350000||o.imported.positions.some(v=>!Number.isFinite(v))))throw Error('Invalid model.');for(const k of ['color','textColor'])if(!/^#[0-9a-f]{6}$/i.test(o[k]))throw Error('Invalid color.')}
if(!/^#[0-9a-f]{6}$/i.test(d.background)||!Number.isInteger(d.active)||d.active<0||d.active>=d.objects.length)throw Error('Invalid scene.');if(!d.brush||!['pen','acrylic','pastel','eraser'].includes(d.brush.type)||!Number.isFinite(d.brush.size)||d.brush.size<.005||d.brush.size>.5||!Number.isFinite(d.light)||!Number.isFinite(d.ambient))throw Error('Invalid scene settings.');
for(const o of d.objects){if(o.imported?.indices&&o.imported.indices.some(i=>!Number.isInteger(i)||i<0||i>=o.imported.positions.length/3))throw Error('Invalid model indices.');if(o.shape==='imported'&&!o.imported)throw Error('Missing model geometry.')}
d.version=2;return d}
$('projectFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>40e6)throw Error('Project exceeds the 40 MB limit.');const d=validateProject(JSON.parse(await f.text()));validateFonts(d.fonts||{});for(const o of d.objects)if(!['mono','slant','sans','serif'].includes(o.font)&&!d.fonts?.[o.font])throw Error('Missing imported font.');state=d;rebuild();switchCamera();setAspect();if(d.camera){camera.position.fromArray(d.camera.position);controls.target.fromArray(d.camera.target);camera.zoom=d.camera.zoom||1;camera.updateProjectionMatrix()}renderSettings();commit();toast('Project opened.')}catch(err){toast(err.message)}finally{e.target.value=''}};
$('modelFile').onchange=async e=>{const files=[...e.target.files],f=files.find(f=>/\.(stl|obj|glb|gltf)$/i.test(f.name));if(!f)return;const urls=[];try{if(files.reduce((n,f)=>n+f.size,0)>35e6)throw Error('Please use a model below 35 MB.');toast('Reading your model…');const buffer=await f.arrayBuffer(),ext=f.name.split('.').pop().toLowerCase();let geometry;if(ext==='stl')geometry=new STLLoader().parse(buffer);else{let obj;if(ext==='obj')obj=new OBJLoader().parse(new TextDecoder().decode(buffer));else{const manager=new THREE.LoadingManager(),fileMap=new Map(files.map(f=>[f.name,f]));manager.setURLModifier(url=>{if(url.startsWith('data:')||url.startsWith('blob:'))return url;const name=decodeURIComponent(url.split('/').pop());const file=fileMap.get(name);if(!file)throw Error('Missing '+name+'. Select the glTF and its companion files together.');const u=URL.createObjectURL(file);urls.push(u);return u});obj=(await new GLTFLoader(manager).parseAsync(buffer,'')).scene}obj.updateMatrixWorld(true);const parts=[];obj.traverse(c=>{if(c.isMesh){let g=c.geometry.clone();if(g.index)g=g.toNonIndexed();g.applyMatrix4(c.matrixWorld);for(const name of Object.keys(g.attributes))if(name!=='position')g.deleteAttribute(name);parts.push(g)}});if(!parts.length)throw Error('No mesh was found in this file.');geometry=mergeGeometries(parts);parts.forEach(g=>g.dispose())}
if(geometry.attributes.position.count>450000)throw Error('Please simplify this model to fewer than 150,000 triangles.');geometry.computeBoundingBox();const box=geometry.boundingBox,size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),scale=3.7/Math.max(size.x,size.y,size.z);if(!Number.isFinite(scale))throw Error('Model contains no usable geometry.');geometry.translate(-center.x,-center.y,-center.z);geometry.scale(scale,scale,scale);const o=defaults();o.shape='imported';o.solid=true;o.coverage=140;o.mapping='project';o.rings=false;o.imported={positions:Array.from(geometry.attributes.position.array),indices:geometry.index?Array.from(geometry.index.array):null};if(o.imported.positions.some(v=>!Number.isFinite(v)))throw Error('Invalid coordinates in model.');state.objects[state.active]=o;geometry.dispose();rebuild();renderSettings();commit();toast('Model imported in grayscale. Add text or paint on its surface.')}catch(err){toast('Import: '+err.message)}finally{urls.forEach(u=>URL.revokeObjectURL(u));e.target.value=''}};

const formatNotes={png:'High-resolution image of the current view. Transparent background is optional. Artboard labels and interface are excluded.',jpeg:'High-resolution image of the current view. JPEG uses your scene background; it does not support transparency.',svg:'Lettering is exported as visible vector paths. Solid forms are embedded as raster images. SVG is available only for projects without painting. This is a 2D projection of the current view.',glb:'A 3D scene with lettering geometry and embedded raster paint textures. Painted areas use a transparent surface carrier, including when solid forms are omitted. Include or omit the solid forms. The background and camera are not embedded.',psd:'Layered Photoshop file: background, solid forms, lettering, and paint. These are raster layers at the current camera angle, not editable fonts or 3D layers. Limited to 2048 px for browser memory.',video:'A full 360° turntable, captured in real time. WebM or MP4 depends on browser support. Video is limited to 2048 px and uses an opaque background. Keep this tab visible while recording.'};
function exportUi(){const painted=hasPainting(),option=$('exportFormat').querySelector('[value="svg"]');option.disabled=painted;option.textContent=painted?'SVG · Clear painting to enable':'SVG · Vector lines';if(painted&&$('exportFormat').value==='svg')$('exportFormat').value='png';const f=$('exportFormat').value;$('exportNote').textContent=formatNotes[f]+(painted?' Raster painting is present: SVG export is disabled.':'');$('exportNow').textContent='Export '+(f==='video'?'movie':f.toUpperCase())+' ↗';$('transparent').disabled=['jpeg','video','glb'].includes(f);$('duration').disabled=f!=='video';$('fps').disabled=f!=='video';$('resolution').disabled=f==='glb'}
$('openExport').onclick=()=>{$('exportSolid').checked=active().solid;exportUi();$('exportDialog').showModal()};$('closeExport').onclick=()=>$('exportDialog').close();$('exportFormat').onchange=exportUi;
function canvasCopy(){const c=document.createElement('canvas');c.width=renderer.domElement.width;c.height=renderer.domElement.height;c.getContext('2d').drawImage(renderer.domElement,0,0);return c}
function blobFrom(c,type='image/png'){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('Image could not be encoded. Try a lower resolution.')),type,.96))}
function exportSetup(size,transparent,include){const old={w:renderer.domElement.clientWidth,h:renderer.domElement.clientHeight,pixel:renderer.getPixelRatio(),background:scene.background};const aspect=$('canvas').clientWidth/$('canvas').clientHeight;const w=Math.round(aspect>=1?size:size*aspect),h=Math.round(aspect>=1?size/aspect:size);renderer.setPixelRatio(1);renderer.setSize(w,h,false);scene.background=transparent?null:new THREE.Color(state.background);renderer.setClearAlpha(transparent?0:1);for(let i=0;i<models.length;i++){models[i].base.material.colorWrite=include;models[i].base.material.depthWrite=include||!state.objects[i].rear}renderer.render(scene,camera);return {w,h,restore(){renderer.setClearAlpha(1);scene.background=old.background;renderer.setPixelRatio(old.pixel);models.forEach((m,i)=>visibility(state.objects[i],m));busy=false;resize();renderer.render(scene,camera)}}}
function renderLayer(kind,include){scene.background=null;renderer.setClearAlpha(0);models.forEach((m,i)=>{const o=state.objects[i];m.base.material.colorWrite=kind==='base'&&include;m.base.material.depthWrite=include||!o.rear;m.text.visible=kind==='text'&&o.textVisible;m.paint.visible=kind==='paint'&&o.paintVisible});renderer.render(scene,camera);return canvasCopy()}
async function exportGlb(include){const root=new THREE.Group();models.forEach((m,i)=>{const group=new THREE.Group();group.position.copy(m.group.position);group.rotation.copy(m.group.rotation);group.scale.copy(m.group.scale);const o=state.objects[i];if(include){const base=m.base.clone();base.material=base.material.clone();base.material.colorWrite=true;base.material.depthWrite=true;group.add(base)}if(o.textVisible)group.add(m.text.clone());if(o.paintVisible)group.add(m.paint.clone());root.add(group)});root.traverse(n=>{n.userData={}});root.updateMatrixWorld(true);const result=await new GLTFExporter().parseAsync(root,{binary:true,onlyVisible:true});download(new Blob([result],{type:'model/gltf-binary'}),'study.glb')}
async function exportSvg(w,h,include,transparent){if(hasPainting())throw Error('SVG is unavailable for painted projects. Export PNG, JPEG, PSD, movie or GLB, or clear the painting first.');let content='';if(!transparent)content+='<rect width="100%" height="100%" fill="'+state.background+'"/>';if(include){const c=renderLayer('base',include);content+='<image width="'+w+'" height="'+h+'" href="'+c.toDataURL()+'"/>'}
models.forEach((m,i)=>visibility(state.objects[i],m));scene.updateMatrixWorld(true);const vp=new THREE.Vector3(),wp=new THREE.Vector3();const occluders=models.filter((m,i)=>include||!state.objects[i].rear).map(m=>m.base);
for(let i=0;i<models.length;i++){const m=models[i],o=state.objects[i];if(!o.textVisible)continue;for(const child of m.text.children){const segments=[];let current=[];for(const point of child.userData.path||[]){wp.fromArray(point).applyMatrix4(m.group.matrixWorld);vp.copy(wp).project(camera);let visible=vp.z>-1&&vp.z<1&&Math.abs(vp.x)<=1&&Math.abs(vp.y)<=1;if(visible&&occluders.length){ray.setFromCamera(new THREE.Vector2(vp.x,vp.y),camera);const distance=wp.distanceTo(ray.ray.origin);ray.far=distance-.035*Math.max(...o.scale);const hit=ray.intersectObjects(occluders,false)[0];ray.far=Infinity;if(hit)visible=false}if(visible)current.push([(vp.x*.5+.5)*w,(-vp.y*.5+.5)*h]);else if(current.length){segments.push(current);current=[]}}if(current.length)segments.push(current);const scale=state.orthographic?h/6*camera.zoom:h/(2*Math.tan(rad(camera.fov)/2)*camera.position.distanceTo(m.group.position));for(const pts of segments){if(pts.length<2)continue;content+='<path d="'+pts.map((p,j)=>(j?'L':'M')+p[0].toFixed(2)+' '+p[1].toFixed(2)).join(' ')+'" fill="none" stroke="'+o.textColor+'" stroke-width="'+(o.stroke*2*scale*Math.max(...o.scale)).toFixed(2)+'" stroke-linejoin="round" stroke-linecap="round"/>'}}}
download(new Blob(['<svg xmlns="http://www.w3.org/2000/svg" width="'+w+'" height="'+h+'" viewBox="0 0 '+w+' '+h+'">'+content+'</svg>'],{type:'image/svg+xml'}),'study.svg')}
async function exportPsd(w,h,include,transparent){const children=[];if(!transparent){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle=state.background;ctx.fillRect(0,0,w,h);children.push({name:'Background',canvas:c})}if(include)children.push({name:'Solid forms',canvas:renderLayer('base',include)});children.push({name:'Lettering',canvas:renderLayer('text',include)},{name:'Painting',canvas:renderLayer('paint',include)});models.forEach((m,i)=>visibility(state.objects[i],m));models.forEach(m=>{m.base.material.colorWrite=include;m.base.material.depthWrite=include||!state.objects[models.indexOf(m)].rear});scene.background=transparent?null:new THREE.Color(state.background);renderer.render(scene,camera);const data=writePsd({width:w,height:h,canvas:canvasCopy(),children},{generateThumbnail:false});download(new Blob([data],{type:'image/vnd.adobe.photoshop'}),'study.psd')}
async function exportVideo(){if(!window.MediaRecorder||!renderer.domElement.captureStream)throw Error('This browser cannot record video. Try Chrome or Edge.');const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('No supported video encoder in this browser.');const fps=+$('fps').value,duration=+$('duration').value,stream=renderer.domElement.captureStream(fps),chunks=[];const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:16000000});const old=world.rotation.y;const wasEnabled=controls.enabled;controls.enabled=false;$('exportProgress').hidden=false;try{await new Promise((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=e=>reject(e.error||Error('Video recording failed.'));recorder.onstop=resolve;recorder.start(100);const start=performance.now();function frame(now){const t=Math.min(1,(now-start)/(duration*1000));world.rotation.y=old+t*Math.PI*2;renderer.render(scene,camera);$('exportProgress').value=t;if(t<1)requestAnimationFrame(frame);else recorder.stop()}requestAnimationFrame(frame)});download(new Blob(chunks,{type:mime}),'study.'+(mime.includes('mp4')?'mp4':'webm'))}finally{stream.getTracks().forEach(t=>t.stop());world.rotation.y=old;controls.enabled=wasEnabled;$('exportProgress').hidden=true}}
$('exportNow').onclick=async()=>{if(busy)return;busy=true;const button=$('exportNow'),f=$('exportFormat').value,include=$('exportSolid').checked,transparent=$('transparent').checked&&!['jpeg','video','glb'].includes(f);button.disabled=true;button.textContent=f==='video'?'Recording turntable…':'Preparing export…';let setup;try{await new Promise(r=>setTimeout(r,60));if(f==='glb')await exportGlb(include);else{let size=+$('resolution').value;if(['psd','video'].includes(f))size=Math.min(size,2048);setup=exportSetup(size,transparent,include);if(f==='png'||f==='jpeg')download(await blobFrom(canvasCopy(),'image/'+f),'study.'+(f==='jpeg'?'jpg':'png'));else if(f==='svg')await exportSvg(setup.w,setup.h,include,transparent);else if(f==='psd')await exportPsd(setup.w,setup.h,include,transparent);else await exportVideo()}toast('Your '+(f==='video'?'movie':f.toUpperCase())+' is ready.')}catch(err){console.error(err);toast('Export: '+err.message)}finally{setup?.restore();busy=false;button.disabled=false;exportUi()}};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_formline_text',title:'Set wrapped lettering',description:'Replace the selected form’s lettering and update the 3D surface.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:250}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.text!=='string'||input.text.length>250)throw Error('Text must be a string of up to 250 characters.');active().text=input.text;rebuild();renderSettings();commit();return {text:active().text,shape:active().shape}}})).catch(()=>{})}catch{}}

$('fontFile').onchange=async e=>{
 const file=e.target.files[0];if(!file)return;
 try{if(file.size>8*1024*1024)throw Error('Choose a font smaller than 8 MB.');
 const data=await registerFontFile(file);state.fonts??={};
 if(Object.keys(state.fonts).length>=8)throw Error('Up to 8 imported fonts per project.');
 state.fonts[data.id]=data;active().font=data.id;rebuild();renderSettings();commit();toast('Font imported. Your letters now follow the surface.');
 }catch(err){toast('Font: '+err.message)}finally{e.target.value=''}
};
$('compositionToggle').onclick=()=>{const open=document.body.classList.toggle('composition-open');$('compositionToggle').setAttribute('aria-expanded',String(open))};
